title: 'Susanna Fort'
default_lang: en
author:
  name: 'Susanna Fort'
  email: susannafm@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Consultora Tecnològica'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
